version: '2.2'
services:
  selenium:
    image: selenium/standalone-chrome-debug
    environment:
      ENVIRONMENT: test
    volumes:
      - /dev/shm:/dev/shm
    ports:
      - 4444:4444
      - 5900:5900
  serverless:
    build:
      dockerfile: serverless.Dockerfile
      context: .
    environment:
      ENVIRONMENT: test
    env_file: .env
    volumes:
      - $PWD:/app
    working_dir: /app
  dynamodb:
    image: amazon/dynamodb-local
    ports:
      - 8000:8000
  python:
    build:
      context: .
    env_file: .env
    environment:
      PIP_NO_CACHE_DIR: "off"
    volumes:
      - $PWD:/app:ro,delegated
    working_dir: /app
    entrypoint: sh
    command:
      - "-c"
      - "echo not meant to be run with the stack"
  vendor:
    extends: python
    entrypoint: pip
    volumes:
      - "$PWD:/app:cached"
      - "$PWD/vendor:/vendor:cached"
      - "$PWD/requirements.txt:/requirements.txt"
    command:
      - download
      - -r
      - /requirements.txt
      - -d
      - /vendor
  lint:
    extends: python
    entrypoint: pylint
    volumes:
      - "$PWD:/app:cached"
    command:
      - -E
  unit:
    extends: python
    entrypoint: pytest
    environment:
      TRIPIT_APP_CLIENT_ID: fake-client-id
      TRIPIT_APP_CLIENT_SECRET: fake-client-secret
    volumes:
      - "$PWD:/app:cached"
    command:
      - -m
      - unit
      - /app/tests
#  unit:
#    extends: ruby
#    entrypoint: rspec
#    environment:
#      LOAD_PATH: "/app/spec/unit;/app/spec;/app/lib"
#      AWS_DYNAMODB_ENDPOINT_URL: "http://dynamodb:8000"
#      ENVIRONMENT: test
#    command:
#      - --tag
#      - unit
#      - --fail-fast
#      - --format
#      - documentation
#  integration:
#    extends: ruby
#    entrypoint: rspec
#    env_file: .env
#    environment:
#      ENVIRONMENT: test
#      LOAD_PATH: "/app/spec/unit;/app/spec;/app/lib"
#      SELENIUM_HOST: selenium
#      SELENIUM_PORT: 4444
#      DISABLE_TRIPIT_CALLBACK_UPDATING: 'true'
#    volumes:
#      - "$PWD/secrets:/secrets"
#    command:
#      - --tag
#      - integration
#      - --fail-fast
#      - --format
#      - documentation
#  integration-setup:
#    extends: serverless
#    entrypoint: bash
#    environment:
#      ENVIRONMENT: test
#    command:
#      - -c
#      - ./scripts/integration_setup.sh
#  integration-teardown:
#    extends: serverless
#    entrypoint: bash
#    environment:
#      ENVIRONMENT: test
#    command:
#      - -c
#      - ./scripts/integration_teardown.sh
