#!/usr/bin/env bash
source $(dirname "$0")/helpers/shared_secrets.sh
source $(dirname "$0")/helpers/logging.sh
ENVIRONMENT="${ENVIRONMENT:-test}"
DEPLOY_FUNCTIONS_ONLY="${DEPLOY_FUNCTIONS_ONLY:-false}"
set -e

usage() {
  cat <<-USAGE
$(basename $0)
Deploys our functions onto serverless infrastructure.

ARGUMENTS

  -h, --help                    Prints this help screen.

ENVIRONMENT VARIABLES

  ENVIRONMENT=test              The environment being deployed into.

  DEPLOY_FUNCTIONS_ONLY=false   Disable re-deploying infrastructure and skip
                                straight to deploying functions.

USAGE
}

if [ "$1" == "-h" ] || [ "$1" == "--help" ]
then
  usage
  exit 0
fi

docker-compose run --rm vendor
case "$ENVIRONMENT" in
  test)
    for stage in deploy-serverless-infra-test deploy-serverless-functions-test
    do
      if test "$stage" == "deploy-serverless-infra-test" && \
        test "$DEPLOY_FUNCTIONS_ONLY" == "true"
      then
        continue
      fi
      docker-compose -f docker-compose.deploy.yml run --rm "$stage"
    done
    ;;
  production)
    for stage in deploy-serverless-infra deploy-serverless-domain deploy-serverless-functions
    do
      docker-compose -f docker-compose.deploy.yml run -e ENVIRONMENT=production --rm "$stage"
    done
    ;;
  *)
    >&2 echo "ERROR: Invalid environment: $ENVIRONMENT"
    exit 1
    ;;
esac
