#!/usr/bin/env sh
GOOGLE_TERRAFORM_SVC_ACCOUNT_CREDS="${GOOGLE_TERRAFORM_SVC_ACCOUNT_CREDS?\
Please specify Google credentials.}"

echo "$GOOGLE_TERRAFORM_SVC_ACCOUNT_CREDS" > /tmp/creds.json
gcloud auth activate-service-account --key-file /tmp/creds.json
exec $*
