#!/usr/bin/env bash
source $(dirname "$0")/helpers/logging.sh
KEEP_ENV_UP="${KEEP_ENV_UP:-false}"
DEPLOY_FUNCTIONS_ONLY="${DEPLOY_FUNCTIONS_ONLY:-false}"
VENDOR_ANYWAY="${VENDOR_ANYWAY:-false}"
NO_DEPLOY="${NO_DEPLOY:-false}"
set -e

usage() {
  cat <<-USAGE
$(basename $0)
Stages our integration environment and runs our integration tests.

ARGUMENTS

  -h, --help                        Prints this help screen.

ENVIRONMENT VARIABLES

  ENVIRONMENT=test                  The environment being deployed into.

  VENDOR_ANYWAY=false               Force dependencies to be downloaded locally.

  DEPLOY_FUNCTIONS_ONLY=false       Disable re-deploying infrastructure and skip
                                    straight to deploying functions.

  KEEP_ENV_UP=false                 Will disable tearing down the integration environment.
                                    Useful if you're running into bugs in integration
                                    that need debugging.

  NO_DEPLOY=false                   Don't deploy anything; use what's available, if anything

USAGE
}

vendor_dependencies() {
  info "Updating app dependencies."
  if ! test -d "./vendor" || grep -Eiq '^true$' <<< "$VENDOR_ANYWAY"
  then
    ! test -d "./vendor" && mkdir "./vendor"
    docker-compose run --rm vendor
  fi
}

update_app_in_integration_service() {
  info "Updating app in integration Docker service."
  docker-compose build integration
}

ensure_selenium_is_running() {
  info "Starting selenium to enable webdriving."
  docker-compose up -d "$(selenium_service)"
}

selenium_service() {
  if grep -Eiq 'arm' <<< "$(uname -m)"
  then
    echo "selenium-arm64"
  else
    echo "selenium-x86_64"
  fi
}

deploy_to_integration() {
  if grep -Eiq '^false$' <<< "$NO_DEPLOY"
  then
    info "Deploying integration environment."
    ENVIRONMENT=test DEPLOY_FUNCTIONS_ONLY="$DEPLOY_FUNCTIONS_ONLY" scripts/deploy
  fi
}

setup() {
  ./scripts/integration_setup.sh
}

teardown() {
  if [ "$KEEP_ENV_UP" == "true" ]
  then
    info "Integration environment will stay up as requested. \
Tear it down by running: docker-compose run --rm integration-teardown."
  else
    scripts/integration_teardown
  fi
}

run_integration_tests() {
  info "Running integration tests."
  SELENIUM_HOST="$(selenium_service)" \
    SELENIUM_PORT=4444 \
    docker-compose run --service-ports --rm integration
}

if [ "$1" == "-h" ] || [ "$1" == "--help" ]
then
  usage
  exit 0
fi

if [ "$DEPLOY_FUNCTIONS_ONLY" != "true" ]
then
  vendor_dependencies
fi
update_app_in_integration_service &&
ensure_selenium_is_running &&
deploy_to_integration &&
setup
run_integration_tests
teardown
